## <center> Numpy
    
Полезные ссылки:
    
https://habr.com/ru/post/352678/

https://pythonworld.ru/numpy

In [2]:
import numpy as np

### Генерация данных

In [84]:
# создание вектора из существующего списка с указанием типа чисел
l = [1, 2, 3]
np.array(l, 'float')

array([1., 2., 3.])

In [85]:
# создание матрицы из существующего списка
l = [[1, 2, 3], 
     [4, 5, 6]]
np.array(l)

array([[1, 2, 3],
       [4, 5, 6]])

In [86]:
# генерация нулевой матрицы
np.zeros((3, 5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [87]:
# генерация единичной матрицы заданной размерности
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [88]:
# генерация чисел в диапазоне с заданным шагом
np.arange(10, 30, 5) # начало, конец (не включается), шаг

array([10, 15, 20, 25])

In [89]:
# генерация заданного количества чисел равномерно заполняющих диапазон
np.linspace(0, 2, 9) # начало, конец (включается), количество чисел в массиве

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  ])

In [90]:
# генерация чисел по правилу основаному на зависимоти от номеров строк и столбцов
np.fromfunction(lambda x, y: x * y, (3, 4), dtype=int)

array([[0, 0, 0, 0],
       [0, 1, 2, 3],
       [0, 2, 4, 6]])

### Генерация случайных чисел

In [94]:
# генерация случайных целых чисел из диапазона 0-1
np.random.sample(5)

array([0.00797585, 0.03518597, 0.82122976, 0.78216846, 0.5898425 ])

In [97]:
# генерация случайных целых чисел из диапазона 0-1
np.random.sample((3,4))

array([[0.01449445, 0.61745786, 0.47911107, 0.80746168],
       [0.48032829, 0.00194012, 0.6861311 , 0.06081057],
       [0.1238706 , 0.48659479, 0.76274877, 0.14939763]])

In [99]:
# генерация случайных целых чисел
np.random.randint(0, 5, 20) # с какого числа, по какое число (не включительно), сколько чисел генерировать

array([1, 4, 2, 1, 4, 2, 3, 0, 3, 3, 4, 3, 1, 1, 0, 2, 0, 4, 0, 0])

In [101]:
# генерация случайных целых чисел
np.random.randint(0, 10, 25).reshape(5,5)

array([[2, 0, 2, 7, 2],
       [8, 8, 8, 8, 9],
       [7, 3, 8, 9, 9],
       [5, 9, 4, 3, 3],
       [6, 0, 3, 8, 7]])

In [102]:
# генерация случайных целых чисел
np.random.randint(0, 3, (2, 5))

array([[0, 1, 2, 2, 0],
       [1, 1, 1, 2, 2]])

In [103]:
# генерация чисел согласно нормальному распределению
np.random.uniform(2, 8, (2, 10))

array([[5.4550482 , 6.72792433, 7.32980467, 5.31373619, 5.09887765,
        3.7113149 , 2.16801571, 7.42900129, 2.88652893, 2.78717196],
       [4.66433504, 2.74151987, 6.02491781, 3.26728093, 6.80134078,
        3.0447289 , 6.93656525, 2.87503954, 3.6607189 , 5.35372489]])

In [105]:
# генерация чисел согласно распределению пуассона
np.random.poisson(2.5, 5)  # 5 numbers, lambda=2.5

array([4, 2, 1, 2, 1])

In [106]:
# генерация чисел согласно биномиальному распределению
np.random.binomial(4, 0.3, 5)  # 5 numbers, n=4, p=0.3

array([3, 1, 1, 1, 1])

In [120]:
np.random.seed(17)
np.random.random(10)

array([0.294665  , 0.53058676, 0.19152079, 0.06790036, 0.78698546,
       0.65633352, 0.6375209 , 0.57560289, 0.03906292, 0.3578136 ])

In [123]:
np.random.seed(1000)
np.random.random(10)

array([0.65358959, 0.11500694, 0.95028286, 0.4821914 , 0.87247454,
       0.21233268, 0.04070962, 0.39719446, 0.2331322 , 0.84174072])

In [128]:
# перемешивание
a = np.arange(10)
np.random.shuffle(a)
a

array([2, 6, 8, 5, 1, 3, 9, 4, 0, 7])

### Базовые операции

In [129]:
# массивы одного размера
a = np.array([20, 30, 40, 50])
b = np.arange(4)
print('массив b:', b)
print('a + b:', a + b)
print('a - b:', a - b)
print('a * b:', a * b)
print('a / b:', a / b)
print('a ** b:', a ** b)
print('a % b:', a % b)
print('a // b:', a // b) 

массив b: [0 1 2 3]
a + b: [20 31 42 53]
a - b: [20 29 38 47]
a * b: [  0  30  80 150]
a / b: [        inf 30.         20.         16.66666667]
a ** b: [     1     30   1600 125000]
a % b: [0 0 0 2]
a // b: [ 0 30 20 16]


C:\Users\Malika\Anaconda3\lib\site-packages\ipykernel_launcher.py:8: RuntimeWarning: divide by zero encountered in true_divide
  
C:\Users\Malika\Anaconda3\lib\site-packages\ipykernel_launcher.py:10: RuntimeWarning: divide by zero encountered in remainder
  # Remove the CWD from sys.path while we load stuff.
C:\Users\Malika\Anaconda3\lib\site-packages\ipykernel_launcher.py:11: RuntimeWarning: divide by zero encountered in floor_divide
  # This is added back by InteractiveShellApp.init_path()


In [130]:
# нельзя сделать операции над массивами разной/несопоставимой размерности 
c = np.array([[1, 2, 3],
              [4, 5, 6]])

d = np.array([[1, 2],
              [3, 4], 
              [5, 6]])
c + d

ValueError: operands could not be broadcast together with shapes (2,3) (3,2) 

In [9]:
# но если совпадает хотя бы одна размерность, то можно
# например, совпадает размерность по столбцам
c = np.array([[1, 2, 3],
              [4, 5, 6]])

d = np.array([10, 20, 30])
c + d

array([[11, 22, 33],
       [14, 25, 36]])

In [7]:
# и так работает
c = np.array([[1, 2, 3], 
              [4, 5, 6]])

d = np.array([10, 20]).reshape(-1,1) # -1 автоподбор количества строк 
d
c + d

array([[11, 12, 13],
       [24, 25, 26]])

In [134]:
a = np.array([[1, 2, 3], [4, 5, 6]])
np.sum(a), a.sum(), a.min(), a.max()

(21, 21, 1, 6)

In [135]:
a.min(axis=0)  # Наименьшее число в каждом столбце

array([1, 2, 3])

In [136]:
a.min(axis=1) # Наименьшее число в каждой строке

array([1, 4])

### Индексы и срезы

In [137]:
a = np.arange(10 ** 3)
a

array([  0,   1,   8,  27,  64, 125, 216, 343, 512, 729], dtype=int32)

In [138]:
a[1] # выбираем один элемент по индексу

1

In [139]:
a[[1, 8, 3]]  # выбираем несколько элементов по индексам

array([  1, 512,  27], dtype=int32)

In [140]:
a[3:7]  # выбираем несколько элементов по диапазону индексов

array([ 27,  64, 125, 216], dtype=int32)

In [141]:
a[3:7] = 8 # меняем несколько элементов по диапазону индексов
a

array([  0,   1,   8,   8,   8,   8,   8, 343, 512, 729], dtype=int32)

In [142]:
a[::-1] # реверс массива

array([729, 512, 343,   8,   8,   8,   8,   8,   1,   0], dtype=int32)

In [143]:
b = np.array([[  0, 1, 2, 3],
              [10, 11, 12, 13],
              [20, 21, 22, 23],
              [30, 31, 32, 33],
              [40, 41, 42, 43]])

In [144]:
 b[2,3]  # Вторая строка, третий столбец

23

In [145]:
b[2][3]  # Можно и так

23

In [146]:
b[:,2]  # Второй столбец

array([ 2, 12, 22, 32, 42])

In [147]:
 b[:2]  # Первые две строки

array([[ 0,  1,  2,  3],
       [10, 11, 12, 13]])

In [148]:
b[1:3, 2: ]  # Вторая и третья строки и со второго столбца до конца

array([[12, 13],
       [22, 23]])

In [149]:
b[-1]  # Последняя строка. Эквивалентно b[-1,:]

array([40, 41, 42, 43])

In [150]:
a = np.array(([[0, 1, 2], [10, 12, 13]], 
              [[100, 101, 102], [110, 112, 113]]))
a.shape # размерность массива

(2, 2, 3)

In [151]:
a.ndim # количесво осей

3

### Операции с формой массива

In [152]:
a

array([[[  0,   1,   2],
        [ 10,  12,  13]],

       [[100, 101, 102],
        [110, 112, 113]]])

In [153]:
c = a.reshape(6,2) # смена размерности массива
c

array([[  0,   1],
       [  2,  10],
       [ 12,  13],
       [100, 101],
       [102, 110],
       [112, 113]])

In [154]:
# итерирование идет по строкам
for r in c:
    print(r)

[0 1]
[ 2 10]
[12 13]
[100 101]
[102 110]
[112 113]


In [155]:
a.ravel()  # Делает массив плоским

array([  0,   1,   2,  10,  12,  13, 100, 101, 102, 110, 112, 113])

In [156]:
c.flatten() # Делает массив плоским

array([  0,   1,   2,  10,  12,  13, 100, 101, 102, 110, 112, 113])

In [157]:
c.transpose()  # Транспонирование

array([[  0,   2,  12, 100, 102, 112],
       [  1,  10,  13, 101, 110, 113]])

### Фильтрация значений

In [158]:
a = np.random.randint(-10, 10, 20).reshape(4,5)
a

array([[ 3,  8, -9,  1,  4],
       [ 5,  5,  7, -5,  1],
       [ 2, -5, -2,  8, -8],
       [ 3, -1, -4,  0,  0]])

In [160]:
a[np.where(a > 0)]
# np.where(a > 0) #координаты

(array([0, 0, 0, 0, 1, 1, 1, 1, 2, 2, 3], dtype=int64),
 array([0, 1, 3, 4, 0, 1, 2, 4, 0, 3, 0], dtype=int64))

In [161]:
a[a>0]

array([3, 8, 1, 4, 5, 5, 7, 1, 2, 8, 3])

In [163]:
a = np.array([1, np.NaN, np.Inf], float)
a

array([ 1., nan, inf])

In [164]:
np.isnan(a)

array([False,  True, False])

In [166]:
np.isfinite(a)

array([ True, False, False])

### Объединение массивов

In [167]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])
np.vstack((a, b))

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [168]:
np.hstack((a, b))

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

### Копии и представления

In [169]:
a = np.arange(12)
b = a  # Нового объекта создано не было
print(b is a)  # a и b это два имени для одного и того же объекта ndarray
b.shape = (3,4)  # изменит форму a
a.shape

True


(3, 4)

In [170]:
c = a.view()
print(c is a) 
print(c.base is a )  # c это представление данных, принадлежащих a

False
True


In [171]:
c.shape = (2,6)  # форма а не поменяется
a.shape

(3, 4)

In [172]:
c[0,4] = 1234  # данные а изменятся
a

array([[   0,    1,    2,    3],
       [1234,    5,    6,    7],
       [   8,    9,   10,   11]])

In [175]:
# Срез массива это представление
s = a[:,1:3]
s[:] = 10
a

array([[   0,   10,   10,    3],
       [1234,   10,   10,    7],
       [   8,   10,   10,   11]])

In [179]:
d = a.copy()  # создается новый объект массива с новыми данными
print(d is a)
print(d.base is a)  # d не имеет ничего общего с а
d[0, 0] = 9999
a

False
False


array([[   0,   10,   10,    3],
       [1234,   10,   10,    7],
       [   8,   10,   10,   11]])