In [1]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import numpy as np

### <center> Задание:

1. Данные представлены двумя файлами, для начала их нужно объединить в один датасет 
2. Необходимо провести анализ и очистку "грязных данных", найти аномалии и выбросы, подумать, как их лучше обработать (скорректировать значения, удалить, оставить и обработать отдельно). Для анализа данных и поиска аномалий рекомендуется использовать в том числе и визуализацию
3. В данных есть пропуски, подумать, как их лучше обработать. Если заполнять, то чем именно лучше заполнить в каждом отдельном случае
4. В конце ноутбука заполнить ячейку **"Отчет по анализу"**, в которой по каждому столбцу описать, ***какие именно аномалии были в нем найдены*** (например, выбросы, пропуски, логичесткие противоречия и т.д.) и как ***обработаны*** (удалены, заменены другим значением и т.д.).  
    
**Важно!**
Нужно постараться **найти и исправить** максимальное количество "косяков" в данных, чтобы на выходе получить чистый набор данных, с которым можно дальше работать. Важно не просто найти, но и обработать "косяк", если он не обработан, то зачтен не будет.

**Максимальное количество баллов за работу - 26**

**Описание данных:**

***data.csv*** 
- **id:** id транзакции
- **timestamp:** дата продажи (транзакции)
- **full_sq:** общая площадь 
- **life_sq:** жилая площадь 
- **floor:** этаж 
- **max_floor:** количество этажей в здании
- **material:** материал, из которого изговолены стены 
- **build_year:** год строительства
- **num_room:** количество жилых комнат
- **kitch_sq:** площадь кухни
- **full_all:** количество населения в регионе
- **state:** жилищные условия
- **sub_area:** название территории
- **price_doc:** цена квартиры (целевая переменная)

***macro.csv***
- **timestamp** : дата, на которую актуальны макроэкономические показатели
- **salary** : средняя зарплата в регионе
- **fixed_basket**: стоимость потребительской корзины
- **rent_price_3room_eco**: стоимость аренды 3-х комнатного жилья эконом-класса
- **rent_price_2room_eco**: стоимость аренды 2-х комнатного жилья эконом-класса
- **rent_price_1room_eco**: стоимость аренды 1-но комнатного жилья эконом-класса
- **average_life_exp**: средняя продолжительность жизни в регионе

In [2]:
data = pd.read_csv('data.csv')
macro = pd.read_csv('data_macro.csv')

In [3]:
df = data.merge(macro)
df

id   timestamp  ...  rent_price_1room_eco  average_life_exp
0      8059  2013-05-21  ...                  2.31             76.37
1      8050  2013-05-21  ...                  2.31             76.37
2      8049  2013-05-21  ...                  2.31             76.37
3      8055  2013-05-21  ...                  2.31             76.37
4      8057  2013-05-21  ...                  2.31             76.37
...     ...         ...  ...                   ...               ...
18861  1992  2012-04-24  ...                 30.89             75.74
18862   500  2011-11-29  ...                 31.53             75.79
18863   669  2011-12-20  ...                 30.74             75.79
18864  2829  2012-07-12  ...                 31.10             75.74
18865  4229  2012-10-16  ...                 32.69             75.74

[18866 rows x 20 columns]

In [4]:
df.describe()

id       full_sq  ...  rent_price_1room_eco  average_life_exp
count  18866.000000  18866.000000  ...          18866.000000      18866.000000
mean   18799.788614     53.940899  ...             33.376801         76.599302
std     7082.428695     44.116185  ...              2.346476          0.229903
min        9.000000      0.000000  ...              2.310000         75.740000
25%    13513.250000     38.000000  ...             32.960000         76.370000
50%    19043.500000     49.000000  ...             33.650000         76.700000
75%    24748.750000     63.000000  ...             34.350000         76.700000
max    30473.000000   5326.000000  ...             35.370000         76.770000

[8 rows x 17 columns]

In [5]:
df.isna().any()

id                      False
timestamp               False
full_sq                 False
life_sq                  True
floor                    True
state                    True
max_floor                True
material                 True
build_year               True
num_room                 True
kitch_sq                 True
full_all                False
sub_area                False
price_doc               False
salary                  False
fixed_basket            False
rent_price_3room_eco    False
rent_price_2room_eco    False
rent_price_1room_eco    False
average_life_exp        False
dtype: bool

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 18866 entries, 0 to 18865
Data columns (total 20 columns):
 #   Column                Non-Null Count  Dtype  
---  ------                --------------  -----  
 0   id                    18866 non-null  int64  
 1   timestamp             18866 non-null  object 
 2   full_sq               18866 non-null  int64  
 3   life_sq               17291 non-null  float64
 4   floor                 18838 non-null  float64
 5   state                 15505 non-null  float64
 6   max_floor             17445 non-null  float64
 7   material              17445 non-null  float64
 8   build_year            16866 non-null  object 
 9   num_room              17445 non-null  float64
 10  kitch_sq              17445 non-null  float64
 11  full_all              18866 non-null  int64  
 12  sub_area              18866 non-null  object 
 13  price_doc             18866 non-null  int64  
 14  salary                18866 non-null  float64
 15  fixed_basket       

# **Колонка 'timestamp'**

In [7]:
df['timestamp'].unique()

array(['2013-05-21', '2013-05-25', '2013-05-27', ..., '2011-12-20',
       '2012-07-12', '2012-10-16'], dtype=object)

In [8]:
df['timestamp'] = pd.to_datetime(df['timestamp'])
df['timestamp']

0       2013-05-21
1       2013-05-21
2       2013-05-21
3       2013-05-21
4       2013-05-21
           ...    
18861   2012-04-24
18862   2011-11-29
18863   2011-12-20
18864   2012-07-12
18865   2012-10-16
Name: timestamp, Length: 18866, dtype: datetime64[ns]

# **Колонка 'state'**



In [9]:
# Проверим странное значение 33
df['state'].unique()

array([ 3., nan,  1.,  2.,  4., 33.])

In [10]:
df['state'].mode()

0    2.0
dtype: float64

In [11]:
# Заменяем все пропуски на моду = 2
# Заменяем странное значение 33 (вероятнее всего случайное двойное нажатие, поэтому заменяем на 3)
df['state'] = df['state'].fillna(2)
df[df['state']==33]
df.loc[714, 'state'] = 3
df['state'].unique()

array([3., 2., 1., 4.])

In [12]:
df.describe()

id       full_sq  ...  rent_price_1room_eco  average_life_exp
count  18866.000000  18866.000000  ...          18866.000000      18866.000000
mean   18799.788614     53.940899  ...             33.376801         76.599302
std     7082.428695     44.116185  ...              2.346476          0.229903
min        9.000000      0.000000  ...              2.310000         75.740000
25%    13513.250000     38.000000  ...             32.960000         76.370000
50%    19043.500000     49.000000  ...             33.650000         76.700000
75%    24748.750000     63.000000  ...             34.350000         76.700000
max    30473.000000   5326.000000  ...             35.370000         76.770000

[8 rows x 17 columns]

# **Колонка 'full_sq'**

In [13]:
df['full_sq'].unique()

array([  11,   63,  101,   37,   92,   53,   42,   35,   77,   45,   61,
         52,   82,   38,   40,   48,   74,   62,   57,   60,   93,   51,
         83,   43,   54,   44,   75,   32,   56,   31,   78,   29,   46,
         79,   39,   41,   59,   33,   55,   58,   65,   71,   30,  114,
         87,   36,  102,   66,   64,   49,  165,   69,   50,  110,  142,
         34,   81,  106,  123,  100,   91,   70,   76,   90,   85,   95,
         47,   23,   67,   73,  136,   84,   99,   28,   14,   68,   80,
         72,   20,   17,   24,  103,  119,   96,   97,   86,  125,  138,
         27,  118,  121,  139,  133,   89,   21,   94,  104,  132,  126,
        155,  116,  143,  117,  112,   19,   25,  113,  107,  122,  144,
          1,  202,  134,   98,  120,  167,   22,  124,  115,   26,  137,
        108,  109,   88,  160,  105,   16,  111,  131,  183,   18,  135,
        215,  174,  149,  146,  127,  153,  303,  189,  172,  186,  220,
        181,  141,  161,  219,  148,    0,  154,  1

In [14]:
for i in range(0,18866,1):
  if df['full_sq'].loc[i]<30:
     df['full_sq'].loc[i]=30

/usr/local/lib/python3.7/dist-packages/pandas/core/indexing.py:670: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  iloc._setitem_with_indexer(indexer, value)


# **Колонка 'life_sq'**

Не успел

# **Колонка 'kitch_sq'**

In [15]:
df['kitch_sq'].fillna(0, inplace=True)
df.describe()

id       full_sq  ...  rent_price_1room_eco  average_life_exp
count  18866.000000  18866.000000  ...          18866.000000      18866.000000
mean   18799.788614     54.083324  ...             33.376801         76.599302
std     7082.428695     44.014858  ...              2.346476          0.229903
min        9.000000     30.000000  ...              2.310000         75.740000
25%    13513.250000     38.000000  ...             32.960000         76.370000
50%    19043.500000     49.000000  ...             33.650000         76.700000
75%    24748.750000     63.000000  ...             34.350000         76.700000
max    30473.000000   5326.000000  ...             35.370000         76.770000

[8 rows x 17 columns]

In [16]:
for i in range(0,18866,1):
  if df['kitch_sq'].loc[i]==0:
     df['full_sq'].loc[i]=5

/usr/local/lib/python3.7/dist-packages/pandas/core/indexing.py:670: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  iloc._setitem_with_indexer(indexer, value)


In [17]:
df['kitch_sq'].head(15)

0     12.0
1      0.0
2      0.0
3      0.0
4      0.0
5      8.0
6      0.0
7      0.0
8     12.0
9      6.0
10     0.0
11     0.0
12     0.0
13     8.0
14     1.0
Name: kitch_sq, dtype: float64

# **Колонка 'floor'**

In [18]:
df['floor'].unique()

array([ 2.,  3.,  6., 10.,  5., 24., 11.,  4., 15., 17., 12., 19.,  1.,
        7.,  8., 16., 13.,  9., nan, 14., 22., 32., 20., 18., 25., 23.,
       21., 37., 30., 28., 26.,  0., 31., 36., 34., 41., 77., 27., 29.,
       44., 33.])

In [19]:
df['floor'].fillna(0, inplace=True)

In [20]:
df['floor'].unique()

array([ 2.,  3.,  6., 10.,  5., 24., 11.,  4., 15., 17., 12., 19.,  1.,
        7.,  8., 16., 13.,  9.,  0., 14., 22., 32., 20., 18., 25., 23.,
       21., 37., 30., 28., 26., 31., 36., 34., 41., 77., 27., 29., 44.,
       33.])

In [21]:
df['floor'].isna().sum()

0

In [22]:
df[df['floor']==77]
df.loc[12018, 'floor'] = 3
df['floor'].unique()

array([ 2.,  3.,  6., 10.,  5., 24., 11.,  4., 15., 17., 12., 19.,  1.,
        7.,  8., 16., 13.,  9.,  0., 14., 22., 32., 20., 18., 25., 23.,
       21., 37., 30., 28., 26., 31., 36., 34., 41., 27., 29., 44., 33.])

In [23]:
df_vibros=df[df['floor'] > df['max_floor']]
df_vibros

id  timestamp  ...  rent_price_1room_eco  average_life_exp
22      8271 2013-05-31  ...                  2.31             76.37
61      8502 2013-06-14  ...                 32.23             76.37
182     8915 2013-07-03  ...                 32.55             76.37
275     9164 2013-07-12  ...                 32.55             76.37
312     9260 2013-07-17  ...                 32.55             76.37
...      ...        ...  ...                   ...               ...
17512  30276 2015-06-16  ...                 30.29             76.77
17538  30302 2015-06-17  ...                 30.29             76.77
17551  30320 2015-06-18  ...                 30.29             76.77
17570  30344 2015-06-20  ...                 30.29             76.77
17607  30394 2015-06-24  ...                 30.29             76.77

[738 rows x 20 columns]

In [24]:
for i in range(0,18866,1):
  if df['floor'].loc[i] > df['max_floor'].loc[i]:
     df['floor'].loc[i] = df['max_floor'].loc[i]

/usr/local/lib/python3.7/dist-packages/pandas/core/indexing.py:670: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  iloc._setitem_with_indexer(indexer, value)


**Проблема, что этаж больше максимального этажа. Но этого не может быть. Но я не знаю, как это корректно обработать...Приравнял максимальный этаж к обычному этажу, но это не совсем корректно получается.**

In [25]:
for i in range(0,18866,1):
  if df['floor'].loc[i]==0:
     df['floor'].loc[i] = df['max_floor'].loc[i]
df[df['floor']==0] 

/usr/local/lib/python3.7/dist-packages/pandas/core/indexing.py:670: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  iloc._setitem_with_indexer(indexer, value)


id  timestamp  ...  rent_price_1room_eco  average_life_exp
61      8502 2013-06-14  ...                 32.23             76.37
182     8915 2013-07-03  ...                 32.55             76.37
364     9426 2013-07-24  ...                 32.55             76.37
725    10089 2013-08-27  ...                 33.15             76.37
748    10145 2013-08-29  ...                 33.15             76.37
...      ...        ...  ...                   ...               ...
17299  30017 2015-05-28  ...                 31.09             76.77
17378  30114 2015-06-04  ...                 30.29             76.77
17408  30143 2015-06-05  ...                 30.29             76.77
17512  30276 2015-06-16  ...                 30.29             76.77
17538  30302 2015-06-17  ...                 30.29             76.77

[179 rows x 20 columns]

In [26]:
df.describe()

id       full_sq  ...  rent_price_1room_eco  average_life_exp
count  18866.000000  18866.000000  ...          18866.000000      18866.000000
mean   18799.788614     48.359112  ...             33.376801         76.599302
std     7082.428695     24.890590  ...              2.346476          0.229903
min        9.000000      5.000000  ...              2.310000         75.740000
25%    13513.250000     37.000000  ...             32.960000         76.370000
50%    19043.500000     45.000000  ...             33.650000         76.700000
75%    24748.750000     61.000000  ...             34.350000         76.700000
max    30473.000000    637.000000  ...             35.370000         76.770000

[8 rows x 17 columns]

# **Колонка 'max_floor'**

In [27]:
df['max_floor'].unique()

array([ 5., nan, 16., 17.,  9., 24.,  1., 10., 25., 14., 12.,  0.,  8.,
       18., 23., 20.,  6., 22.,  7.,  4., 30., 11.,  3., 40., 32., 15.,
       27.,  2., 19., 28., 29., 39., 38., 13., 31., 21., 26., 37., 33.,
       47., 36., 34., 48., 42., 57., 44., 45., 41.])

In [28]:
df_vibros=df[df['floor'] > df['max_floor']]
df_vibros

Empty DataFrame
Columns: [id, timestamp, full_sq, life_sq, floor, state, max_floor, material, build_year, num_room, kitch_sq, full_all, sub_area, price_doc, salary, fixed_basket, rent_price_3room_eco, rent_price_2room_eco, rent_price_1room_eco, average_life_exp]
Index: []

# **Колонка 'material'**


In [29]:
df['material'].mode()

0    1.0
dtype: float64

In [30]:
df['material'].fillna(1, inplace=True)
df.describe()

id       full_sq  ...  rent_price_1room_eco  average_life_exp
count  18866.000000  18866.000000  ...          18866.000000      18866.000000
mean   18799.788614     48.359112  ...             33.376801         76.599302
std     7082.428695     24.890590  ...              2.346476          0.229903
min        9.000000      5.000000  ...              2.310000         75.740000
25%    13513.250000     37.000000  ...             32.960000         76.370000
50%    19043.500000     45.000000  ...             33.650000         76.700000
75%    24748.750000     61.000000  ...             34.350000         76.700000
max    30473.000000    637.000000  ...             35.370000         76.770000

[8 rows x 17 columns]

**Также, наверное, неправильное исправление. Но так и не смог придумать, как сделать лучше :(**

# **Колонка 'build_year'**

In [31]:
df['build_year'].unique()

array(['1907.0', nan, '1980.0', '2014.0', '1970.0', '1982.0', '2013.0',
       '2004.0', '2003.0', '1957.0', '1986.0', '1960.0', '1995.0',
       '1979.0', '1975.0', '1987.0', '1962.0', '1969.0', '1993.0',
       '1996.0', '1972.0', '2011.0', '1965.0', '2010.0', '1985.0',
       '2006.0', '1961.0', '1971.0', '1978.0', '1966.0', '1967.0',
       '2000.0', '1964.0', '1977.0', '1983.0', '1968.0', '1974.0',
       '2008.0', '1959.0', '2007.0', '1984.0', '1976.0', '1997.0',
       '1989.0', '1958.0', '1988.0', '2012.0', '1990.0', '1946.0',
       '1917.0', '2002.0', '2005.0', '2001.0', '1963.0', '1954.0',
       '1951.0', '1981.0', '1955.0', '1999.0', '2009.0', '1973.0',
       '1994.0', '1998.0', '1992.0', '1950.0', '1956.0', '2015.0', '0.0',
       '1932.0', '1.0', '1937.0', '1938.0', '1939.0', '1991.0', '1934.0',
       '1935.0', '20052009.0', '1947.0', '1953.0', '1933.0', '2016.0',
       '1930.0', '1912.0', '1929.0', '3.0', '1928.0', '1915.0', '1936.0',
       '1925.0', '1940.0', '1943

In [32]:
# Смена буквы о на 0
df['build_year']=df['build_year'].fillna(0)
df=df.replace({'build_year' : { 'o': 0}})

In [33]:
df['build_year'].unique()

array(['1907.0', 0, '1980.0', '2014.0', '1970.0', '1982.0', '2013.0',
       '2004.0', '2003.0', '1957.0', '1986.0', '1960.0', '1995.0',
       '1979.0', '1975.0', '1987.0', '1962.0', '1969.0', '1993.0',
       '1996.0', '1972.0', '2011.0', '1965.0', '2010.0', '1985.0',
       '2006.0', '1961.0', '1971.0', '1978.0', '1966.0', '1967.0',
       '2000.0', '1964.0', '1977.0', '1983.0', '1968.0', '1974.0',
       '2008.0', '1959.0', '2007.0', '1984.0', '1976.0', '1997.0',
       '1989.0', '1958.0', '1988.0', '2012.0', '1990.0', '1946.0',
       '1917.0', '2002.0', '2005.0', '2001.0', '1963.0', '1954.0',
       '1951.0', '1981.0', '1955.0', '1999.0', '2009.0', '1973.0',
       '1994.0', '1998.0', '1992.0', '1950.0', '1956.0', '2015.0', '0.0',
       '1932.0', '1.0', '1937.0', '1938.0', '1939.0', '1991.0', '1934.0',
       '1935.0', '20052009.0', '1947.0', '1953.0', '1933.0', '2016.0',
       '1930.0', '1912.0', '1929.0', '3.0', '1928.0', '1915.0', '1936.0',
       '1925.0', '1940.0', '1943.0

# <center> **Отчет по анализу:**

- **id:** 
- **timestamp:** Тип object сменил на datetime
- **full_sq:** Минимальное значение 0, заменил на 30
- **life_sq:**  Пропуски, Минимальное значение 0 (но не исправил)
- **floor:**  Пропуски, Минимальное значение 0, есть выброс - 77 (2 раза нажали 7)
- **max_floor:** Пропуски, Минимальное значение 0
- **material:**  Пропуски
- **build_year:** Пропуски, буква о вместо 0
- **num_room:** Пропуски, Минимальное значение 0 (также не сделал)
- **kitch_sq:** Пропуски
- **full_all:** 
- **state:** есть пропуски, есть выброс - 33 (2 раза нажали 3 возможно)
- **sub_area:** 
- **price_doc:** 
- **timestamp** :
- **salary** : 
- **fixed_basket**: 
- **rent_price_3room_eco**: 
- **rent_price_2room_eco**: 
- **rent_price_1room_eco**: 
- **average_life_exp**: 